"""add_metrics_field_to_model

Revision ID: fb8f5f4e5a27
Revises: 7ad16c93b0ff
Create Date: 2025-10-05 14:32:41.654015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb8f5f4e5a27'
down_revision: Union[str, Sequence[str], None] = '7ad16c93b0ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('metrics', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'metrics')
    # ### end Alembic commands ###
